server:
  port: 8080

spring:
  application:
    name: "CrediYAAuthService"

  devtools:
    add-properties: false

  flyway:
    url: jdbc:mysql://localhost:3306/crediya
    user: crediya_user
    password: crediya_pass
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: crediya
    username: crediya_user
    password: crediya_pass